name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # This can be changed to any branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: 22f2005138-tdsp1:latest

    # Step 4: Build the Docker image
    #- name: Build Docker image
    #  run: |
    #    docker build -t ${{ secrets.DOCKER_USERNAME }}/22f2005138_TDSP1:${{ github.sha }} .
      
    # Step 5: Push the Docker image to Docker Hub
    # - name: Push Docker image
    #  run: |
    #    docker push ${{ secrets.DOCKER_USERNAME }}/22f2005138_TDSP1:${{ github.sha }}

    #- name: Push Docker image
    #  run: |
    #    docker push ${{ secrets.DOCKER_USERNAME }}/22f2005138-TDSP1:${{ github.sha }}
    #    docker tag ${{ secrets.DOCKER_USERNAME }}/22f2005138-TDSP1:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/22f2005138-TDSP1:latest
    #    docker push ${{ secrets.DOCKER_USERNAME }}/22f2005138-TDSP1:latest

