name: Daily commit for the TDS Project 1

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: "0 3 * * *"
  workflow_dispatch: # Allow manual triggers

jobs:
  create-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 23f2005138@ds.study.iitm.ac.in 
        run: echo 'Testing the scheduled run for TDS Week 4, Q.9'
      
        
      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add *
          git commit -m "Daily commit for TDS Project 1 Repo" || exit 0
          git push
